---
- hosts: web_portal
  tasks:
    - name: Apt get update
      apt: update_cache=yes

    - name: Install apache2, nginx, nmap
      apt: name={{ item }}  update_cache=no
      with_items:
       - apache2
       - nginx
       - nmap

    - name: copy data files
      copy: src=index.html dest=/var/www/html/
      register: copy_status

    - name: Stop the service
      service: name=apache2 state=stopped

    - name: Copy template file
      template: src=current.html.j2 dest=/var/www/html/current.html
      notify: 
        - Start apache

#    - name: print hostname
#      debug: var=ansible_hostname

    - name: Testing conditional
      shell: uptime
      when: ansible_hostname == "ip-10-0-1-127"

    - name: Testing until
      shell: service apache2 status
      register: result
      until: result.stdout.find("active (running)") != -1
      retries: 5
      delay: 5

#    - name: Check uptime
#      shell: uptime
#      register: uptime_var

#    - name: Print uptime
#      debug:
#        var: uptime_var
   
#    - name: Copy status
#      debug: var=copy_status

  handlers:
    - name: Start apache
      service: name=apache2 state=restarted
